name: 'Test and lint code when pushed to Github'
on:
    push:
jobs:
    test:
        runs-on: ubuntu-latest
        name: Test the application
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Dependancies
              run: npm install
            - name: Test application
              run: npm test
            - name: Lint Code
              run: npm run lint